### PR TITLE
install mirage-solo5.pc to lib/pkconfig (instead of share/pkgconfig)

### PR DESCRIPTION
**Pull request by hannesm**
this requires topkg 0.9.0 and opam2

### CODE REVIEW

**Comment by hannesm** [comment]
@emillon I think this is independent of your opam-repository PR (which, IIUC, once merged, can remove lots of `export PKG_CONFIG_PATH ...` in various build systems across the mirage ecosystem)

**Comment by emillon** [comment]
Ah, right there's no dependency ! :+1:

**Comment by mato** [comment]
Just a sanity check here, have you verified that this works as expected, and the `.pc` file does indeed get installed in `lib/pkgconfig`?

**Comment by hannesm** [comment]
@mato yes, and I also checked that `mirage configure -t hvt` followed by `mirage build` works for a hello world unikernel (with `~/.opam/4.07.1/share/pkgconfig` being empty) :)

**Comment by mato** [comment]
Thanks, this looks fine then (and is orthogonal to the change in ocaml/opam-repository#13042). Merging.

**Pull request merged**
