### PR TITLE
Add caml_get_addr

### PR DESCRIPTION
**Pull request by djs55**
This is the stub originally from [mirage/io-page#29]

Rename matches https://github.com/mirage/io-page/pull/48

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by yallop** [comment]
It'd probably be better for this (and `caml_alloc_pages`) to avoid the `caml_` prefix, which I think may be reserved for the OCaml distribution.

**Comment by djs55** [comment]
Thanks -- did you mention that before? I've got a feeling of déjà vu

**Comment by yallop** [comment]
> déjà vu

(I'm sure I've heard that expression somewhere recently[.](https://github.com/ocaml/ocaml/pull/1201#issuecomment-308486437))

And you're quite right: I mentioned the `caml_` issue on a related pr a few weeks ago (https://github.com/mirage/io-page/pull/39#discussion_r117005926)

**Comment by mato** [comment]
Will/should there be a general renaming of stubs to use the `mirage_` prefix? I have some Solo5 API changes queued up which also include a general cleanup of the Solo5 C bindings (see https://github.com/Solo5/solo5/issues/200), so any further renaming can be done as part of that since it's already a breaking change.

**Comment by djs55** [comment]
I think there should be a general renaming -- if you've got some changes queued up then that sounds like a convenient place to do it. To be honest I only did this one because I had to add `foo_get_addr` anyway after https://github.com/mirage/io-page/pull/29 and to be honest I only merged that thinking it would be a simple fairly localised change -- having to make a change here was a surprise to me! :)

**Pull request merged**
