### PR TITLE
Port to dune, using exposed flags from ocaml-freestanding, and separate common and internal APIs

### PR DESCRIPTION
**Pull request by TheLortex**
Instead of doing https://github.com/mirage/mirage-solo5/pull/44 we can starting by having ocaml-freestanding ported to dune and separating shared and solo5-specific APIs. The second step would be to set mirage-solo5 as an implementation of mirage-os-shim's interface. 

This breaks API for `mirage-block-solo5` and `mirage-net-solo5` so I've made the corresponding PRs.

### CODE REVIEW

**Comment by mato** [comment]
@TheLortex What exactly is being addressed here, and why does it require an API change for `mirage-block-solo5` and `mirage-net-solo5`? There seem to be a lot more changes than what I'd expect for a PR that ports the _existing_ code to use `dune` as a build system.

**Comment by TheLortex** [comment]
@mato The scope of this PR is a bit broader than  _simply_ changing the build system. Switching to `dune` unveiled an issue which is that there's no definition of a common API between mirage OS backends. For now it's enforced by unwritten conventions, using `dune`'s virtual libraries, we can instead explicitly define what _is_ the common interface and enforce it by the build system. The common interface name is `OS`, defined in the `mirage-os-shim` package. This means the OS-specific interface should move in it's own module, named `Os_solo5` (or any capitalization you prefer actually..). This means `mirage-block-solo5` and `mirage-net-solo5` have to use `Os_solo5` instead of `OS` to use solo5 APIs.

Does that seem right to you ?

**Comment by mato** [comment]
@TheLortex:

> The scope of this PR is a bit broader than simply changing the build system. Switching to dune unveiled an issue which is that there's no definition of a common API between mirage OS backends.

That's right, the backends do have various "private" interfaces in `OS` which are not codified anywhere.

> For now it's enforced by unwritten conventions, using dune's virtual libraries, we can instead explicitly define what is the common interface and enforce it by the build system. The common interface name is OS, defined in the mirage-os-shim package. 

I thought `mirage-os-shim` was a "workaround" to get a common `OS` interface where there is none, for those packages that need one. If I understand you correctly, you're proposing `mirage-os-shim` become a first-class package in Mirage and have it define `OS`?

> This means the OS-specific interface should move in it's own module, named Os_solo5 (or any capitalization you prefer actually..). 

`OS_Solo5` (and, correspondingly `OS_Xen`, `OS_Unix`) read much better to me.

> Does that seem right to you ?

Two things:

1. I'd still prefer, if at all possible, to split part (a) "port mirage-solo5 to dune" and (b) "fix the common OS interface" into separate PRs. If nothing else (b) will require much more work, and more inter-dependent package releases, so it'll take longer to actually get done.
2. My experience with the OCaml module system is not good enough to give an opinion on whether or not this particular arrangement (as you propose above) is the right way forward, so I'd like others from @mirage/core to comment on this before proceeding.

**Comment by dinosaure** [comment]
> My experience with the OCaml module system is not good enough to give an opinion on whether or not this particular arrangement (as you propose above) is the right way forward, so I'd like others from @mirage/core to comment on this before proceeding.

The idea behind this PR is to propose a common abstraction of an OS without implementation. Then, `xen` and `solo5` will provide implementations under interface provided by `mirage-os-shim`.

From what I see on this PR, it's much more a _glue_ needed to homogenize _backends_ needed for a _dunification_ of MirageOS.

However, I agree that a split into 2 PR:
- `dune` patch
- API update

will be more easier and better to read.

**Pull request closed without merging**
