### PR TITLE
remove Env module from OS -- the only symbol, argv, returns an empty array

### PR DESCRIPTION
**Pull request by hannesm**
There is a way to receive boot parameters via the argv device of Mirage

### CODE REVIEW

**Comment by hannesm** [comment]
see https://github.com/pqwy/mirage-os-shim/pull/2 and https://github.com/mirage/mirage-platform/pull/187

**Comment by mato** [comment]
This change looks fine to me. To confirm: Due to the API change it'll need a point release cut so that downstream consumers (mirage-os-shim, anyone else?) have a version to constrain against?

**Comment by hannesm** [comment]
On 05/06/2017 11:30, Martin Lucina wrote:
> This change looks fine to me. To confirm: Due to the API change it'll need a point release cut so that downstream consumers (mirage-os-shim, anyone else?) have a version to constrain against?

Yes, AFAICS mirage-os-shim is the only user of this module -- so it will
need a mirage-os-shim release first.

**Comment by hannesm** [comment]
i'll close for now and revive once there's a mirage-os (and/or mirage-os-shim is updated)

**Pull request closed without merging**
