### PR TITLE
Port to topkg

### PR DESCRIPTION
**Pull request by mato**
The main goals here are to eradicate OASIS, and have a less fragile build system.

Remaining problems:
1. The `OS` module is still not seen by the build system, eg. `mirage-console` example, or `mirage-os-shim` package fail with `Unbound module OS.Main`.
1. `lib/bindings/mirage-solo5.pc` needs to be installed in `lib/pkgconfig`. Unfortunately there's no way to do this with an OPAM install file (and thus topkg).
1. Technically we don't want to build a `lib/dllmirage-solo5_bindings.so` at all, is there any way to disable this?

For point (2) above I can see three options:
1. Use `share/pkgconfig` for `.pc` files and `share_root` to install. Everything in the `pkgconfig` universe and the `mirage` tool is currently using `lib/pkgconfig` so these would need to be updated. (Technically `share/` _is_ the correct place for this).
2. As for (1) but do some kind of symlink hack in `conf-pkgconfig` to not have to update the whole pkg-config-using universe.
3. It _might_ be possible to drop the `mirage-solo5.pc` altogether and rely on _something_ in ocamlbuild/META to link in `libmirage-solo5_bindings.a` but I'm not sure what that something is. Would still need a bunch of changes in `mirage` but less than (1) above.

@pqwy @hannesm @avsm I'm somewhat out of my depth in OCaml build systems here. Would appreciate your review and help with the above points. Also cc @yomimono @dbuenzli

### CODE REVIEW

**Comment by hannesm** [comment]
1) can be solved by putting a `module Main : sig .. end` into `oS.mli`
2) I agree and went through some trouble to get this through (it is a minor change in the mirage tool, but it spans over solo5, ocaml-freestanding, mirage-solo5, gmp-freestanding, ocb-stubblr, and then the xen side: minios-xen, mirage-xen-minios, mirage-xen-posix, mirage-xen-ocaml, mirage-xen, gmp-xen)  I think it is worth it (and will file a tracking issue on mirage, and post this issue to the mailing list)

I prepared https://github.com/mato/mirage-solo5/pull/1 for the changes needed on your branch.

**Comment by dbuenzli** [comment]
> lib/bindings/mirage-solo5.pc needs to be installed in lib/pkgconfig. Unfortunately there's no way to do this with an OPAM install file (and thus topkg).

Yes you can via `Pkg.lib "lib/bindings/mirage-solo5.pc" ~dst:"../pkgconfig/"`

**Comment by pqwy** [comment]
@mato 

> Technically we don't want to build a lib/dllmirage-solo5_bindings.so at all, is there any way to disable this?

Not if you are using `.clib` because `ocamlmklib` does both as soon as you request `libBASE.a`, but this is harmless.

You should not install it, though. AFAICT there is no `Pkg.field` that does nothing, so either try something like

```
let nowhere ?force ?built ?cond ?exts ?dst _ = Pkg.nothing
...
Pkg.clib ~dllfield:nowhere "lib/libmirage-solo5_bindings.clib"
```

or play with `Pkg.lib`.

**Comment by pqwy** [comment]
> It might be possible to drop the mirage-solo5.pc altogether and rely on something in ocamlbuild/META to link in libmirage-solo5_bindings.a but I'm not sure what that something is. Would still need a bunch of changes in mirage but less than (1) above.

ATM using `pkg-config` means that supporting Mirage-multilib is just a special case of tagging build artefacts with data from `pkg-config`, which is needed in other places too. I much prefer that uniformity to a homegrown logic.

**Comment by mato** [comment]
So, the relative-path trick for installing the `.pc` file works for me, but I really don't want to depend on that behaviour. There is no ideal solution (@talex5's comments understood), in order to progress this I think the best option is to use `Pkg.share_root` here in combination with mirage/mirage#669.

**Pull request merged**
